name: Testcases for webapp

on:
  pull_request:
    branches:
      - main  
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: Testdb
          MYSQL_USER: Tester
          MYSQL_PASSWORD: TestPassword
          MYSQL_ROOT_PASSWORD: TestPassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Create .env File
        run: |
          echo "DB_name=Testdb" >> .env
          echo "DB_username=Tester" >> .env
          echo "DB_password=TestPassword" >> .env
          echo "DB_host=127.0.0.1" >> .env
          echo "PORT=3000" >> .env
          echo "DEFAULT_PORT=3001" >> .env

      - name: Wait for MySQL to be Ready
        run: |
          until mysql -h 127.0.0.1 -P 3306 -uTester -pTestPassword -e "SELECT 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 10
          done

      - name: Start Server in the Background
        run: nohup npm start &
        env:
          DB_name: TestDb
          DB_username: Tester
          DB_password: TestPassword
          DB_host: 127.0.0.1
          PORT: 3000
          DEFAULT_PORT: 3001

      - name: Run Test-Cases
        run: npm test -- --exit

      - name: Stop Server
        run: |
          PID=$(lsof -t -i:3001) && kill $PID || echo "Server not running"
          
